Revert "ci: ブランチ名をチェックする条件文を変更"
This reverts commit c22870b4287fcdd32a0e0ce1c0a8050af74d3836.

diff --git a/.github/workflows/check-mergable-branch.yml b/.github/workflows/check-mergable-branch.yml
--- a/.github/workflows/check-mergable-branch.yml
+++ b/.github/workflows/check-mergable-branch.yml
@@ -12,7 +12,9 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Fail if branch name does not start with feature/ or hotfix/
-        if: ${{ !startsWith(github.head_ref, 'feature') && !startsWith(github.head_ref, 'hotfix')  }}
         run: |
-          echo "Error: Branch names should start with 'feature/' or 'hotfix/'."
-          exit 1
+          BRANCH_NAME=${{ github.head_ref }}
+          if [[ ! $BRANCH_NAME == feature/* ]] && [[ ! $BRANCH_NAME == hotfix/* ]]; then
+            echo "Error: Branch names should start with 'feature/' or 'hotfix/'."
+            exit 1
+          fi
